import {mathSkills,mathSkillResources} from '../data/mathSkills.js';
export const PROFILE_KEY='atollingo_user_profile', PROGRESS_KEY='atollingo_learning_progress', IDENTITY_KEY='atollingo_unified_identity', FAMILY_KEY='atollingo_family_v1';
export const LEVEL_MATRIX={1:[1,2,3],2:[2,3,4],3:[3,4,5],4:[4,5,6],5:[5,6,7]};
export const SKILLS={...mathSkills,'ENG_G1_R1':'Letter sounds','ENG_G1_R2':'Blending words','ENG_G1_R3':'Sight words & nouns','ENG_G1_SL1':'Action verbs','ENG_G1_W1':'Descriptive adjectives','ENG_G1_W2':'Sentence building & punctuation'};
export function readLocal(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
export function writeLocal(key,value){localStorage.setItem(key,JSON.stringify(value));emit()}
function emit(){if(typeof window!=='undefined')window.dispatchEvent(new Event('atollingo-change'))}
export function calculatedLevel(grade,difficulty){return LEVEL_MATRIX[grade]?.[['Easy','Medium','Hard'].indexOf(difficulty)]||1}
const emptyProgress=()=>({activities:[],badges:[],stars:0,skills:{},lastActivity:null});
const validId=id=>typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
function validProfile(p){return p&&validId(p.studentId)&&validId(p.familyId)&&typeof p.displayName==='string'&&p.displayName.trim().length>0&&p.displayName.length<=40&&Number.isInteger(p.grade)&&p.grade>=1&&p.grade<=5&&['Easy','Medium','Hard'].includes(p.difficulty)&&(['dilu_dolphin','tara_turtle','crabby'].includes(p.avatarId)||/^avatar-(0[1-9]|1[0-8])$/.test(p.avatarId))}
export function getFamily(){let f=readLocal(FAMILY_KEY,null);if(f?.version===1&&Array.isArray(f.profiles)&&f.profiles.every(validProfile)&&f.profiles.length<=4&&f.progress&&typeof f.progress==='object'&&(f.activeId===null||f.profiles.some(p=>p.studentId===f.activeId)))return f;const old=readLocal(IDENTITY_KEY,null)||readLocal(PROFILE_KEY,null);f={version:1,familyId:crypto.randomUUID(),activeId:null,profiles:[],progress:{}};if(old&&(old.displayName||old.name)){const p={studentId:crypto.randomUUID(),familyId:f.familyId,displayName:String(old.displayName||old.name).slice(0,40),grade:Math.min(5,Math.max(1,Number(old.grade)||1)),difficulty:['Easy','Medium','Hard'].includes(old.difficulty)?old.difficulty:'Medium',avatarId:'dilu_dolphin'};p.calculatedLevel=calculatedLevel(p.grade,p.difficulty);f.profiles=[p];f.activeId=p.studentId;const oldProgress=readLocal(PROGRESS_KEY,emptyProgress());f.progress[p.studentId]=Array.isArray(oldProgress.activities)&&oldProgress.skills?oldProgress:emptyProgress()}localStorage.setItem(FAMILY_KEY,JSON.stringify(f));return f}
function saveFamily(f){localStorage.setItem(FAMILY_KEY,JSON.stringify(f));const p=f.profiles.find(p=>p.studentId===f.activeId)||null;try{localStorage.setItem(PROFILE_KEY,JSON.stringify(p));localStorage.setItem(IDENTITY_KEY,JSON.stringify(p));localStorage.setItem(PROGRESS_KEY,JSON.stringify(f.progress[f.activeId]||emptyProgress()))}catch{/* Canonical family save succeeded; mirrors are optional. */}emit()}
export function getProfile(){const f=getFamily();return f.profiles.find(p=>p.studentId===f.activeId)||null}
export function getProfiles(){return getFamily().profiles}
export function getProgress(studentId){const f=getFamily();return f.progress[studentId||f.activeId]||emptyProgress()}
export function saveProfile(input){const f=getFamily();const existing=input.studentId&&f.profiles.find(p=>p.studentId===input.studentId);if(!existing&&f.profiles.length>=4)throw Error('This browser already has four child profiles.');const p={...input,studentId:existing?.studentId||crypto.randomUUID(),familyId:f.familyId,displayName:String(input.displayName||'').trim(),calculatedLevel:calculatedLevel(input.grade,input.difficulty)};if(!validProfile(p))throw Error('Enter a name, grade, challenge and avatar.');f.profiles=existing?f.profiles.map(x=>x.studentId===p.studentId?p:x):[...f.profiles,p];f.activeId=p.studentId;f.progress[p.studentId]??=emptyProgress();saveFamily(f);return p}
export function switchProfile(id){const f=getFamily();if(!f.profiles.some(p=>p.studentId===id))throw Error('Profile not found.');f.activeId=id;saveFamily(f)}
export function setLastActivity(activity){const f=getFamily();if(!f.activeId)return;const href=safeActivityHref(activity.href);f.progress[f.activeId]??=emptyProgress();f.progress[f.activeId].lastActivity={title:String(activity.title).slice(0,100),href};saveFamily(f)}
export function safeActivityHref(href){if(typeof href!=='string')return '/learn';try{const u=new URL(href,'https://atollingo.com');if(!['https://atollingo.com','https://english.atollingo.com','https://play.atollingo.com','https://worksheets.atollingo.com','https://arabic.atollingo.com','https://lagoon.mathlagoon.com','https://mathlagoon.com','https://explorer.mathlagoon.com','https://worksheets.mathlagoon.com'].includes(u.origin))return '/learn';return u.origin==='https://atollingo.com'?u.pathname+u.search:u.href}catch{return '/learn'}}
export function mastery(accuracy){return accuracy<70?'Needs Practice':accuracy<90?'Proficient':'Mastered'}
export function getSkillMasteryStatus(skillId,studentId){const s=getProgress(studentId).skills[skillId];return s?mastery(s.accuracy):'Not started'}
export function recordActivityCompletion(skillId,appName,score,starsEarned,options={}){
 if(!SKILLS[skillId]||!['OceanLearn','OceanPlay','Worksheets','OceanArabic','MathLagoon'].includes(appName)||!Number.isFinite(score)||score<0||score>100||!Number.isInteger(starsEarned)||starsEarned<0||starsEarned>3)throw Error('Invalid activity result.');
 const f=getFamily(),studentId=options.studentId||f.activeId;if(!f.profiles.some(p=>p.studentId===studentId))throw Error('Choose a learner first.');const p=f.progress[studentId]||emptyProgress(),id=options.id||crypto.randomUUID();if(p.activities.some(a=>a.id===id))return p;
 const a={id,skillId,appName,score,starsEarned,at:new Date().toISOString(),seconds:Math.min(1800,Math.max(0,Number(options.seconds)||0))};p.activities=[...p.activities,a].slice(-2000);const recent=p.activities.filter(a=>a.skillId===skillId).slice(-3);p.skills[skillId]={title:SKILLS[skillId],accuracy:Math.round(recent.reduce((s,a)=>s+a.score,0)/recent.length),lastPractised:a.at};p.stars+=starsEarned;if(mathSkillResources[skillId])p.lastActivity={title:SKILLS[skillId],href:mathSkillResources[skillId].href};
 if(!p.badges.some(b=>b.id===skillId)&&score>=70)p.badges.push({id:skillId,title:`${SKILLS[skillId]} explorer`,at:a.at});f.progress[studentId]=p;saveFamily(f);
 const assignments=readLocal('atollingo_assignments',[]);let changed=false;for(const task of assignments){if(task.studentId===studentId&&task.skillId===skillId&&(!task.appName||task.appName===appName)&&!task.completed){task.completed=true;changed=true}}if(changed)writeLocal('atollingo_assignments',assignments);return p;
}
export function getConnectedNextStep(skillId,studentId){if(mathSkillResources[skillId])return {...mathSkillResources[skillId],mode:'lesson'};if(!SKILLS[skillId])return null;const a=getProgress(studentId).activities.filter(a=>a.skillId===skillId).at(-1);const mode=!a?'lesson':a.appName==='OceanLearn'?'game':a.appName==='OceanPlay'?'worksheet':'lesson';const origins={lesson:'https://english.atollingo.com',game:'https://play.atollingo.com',worksheet:'https://worksheets.atollingo.com'};return {mode,title:mode==='lesson'?'Learn this skill':mode==='game'?'Play the matching game':'Try the matching worksheet',href:`${origins[mode]}/connected?skill=${skillId}&mode=${mode}`}}
export function exportProgressBackup(){return JSON.stringify({kind:'atollingo-backup',version:1,family:getFamily(),assignments:readLocal('atollingo_assignments',[]),classes:readLocal('atollingo_classes',[])},null,2)}
export function validateBackup(raw){if(typeof raw!=='string'||raw.length>5_000_000)throw Error('Choose a backup smaller than 5 MB.');let b;try{b=JSON.parse(raw)}catch{throw Error('This file is not valid JSON.')}const f=b?.family;if(b.kind!=='atollingo-backup'||b.version!==1||f?.version!==1||!Array.isArray(f.profiles)||f.profiles.length>4||!f.profiles.every(validProfile)||new Set(f.profiles.map(p=>p.studentId)).size!==f.profiles.length||(f.profiles.length?!f.profiles.some(p=>p.studentId===f.activeId):f.activeId!==null)||!validId(f.familyId)||!f.progress)throw Error('This is not a supported Atollingo backup.');for(const profile of f.profiles){const p=f.progress[profile.studentId];if(profile.familyId!==f.familyId||!p||!Array.isArray(p.activities)||p.activities.length>2000||!Number.isFinite(p.stars)||p.stars<0||!Array.isArray(p.badges)||!p.skills)throw Error('Backup progress is invalid.');for(const b of p.badges)if(typeof b.id!=='string'||typeof b.title!=='string')throw Error('Invalid badge data.');for(const a of p.activities)if(typeof a.id!=='string'||!Number.isInteger(a.starsEarned)||a.starsEarned<0||a.starsEarned>3||(a.skillId!=='UNMAPPED'&&(!SKILLS[a.skillId]||!Number.isFinite(a.score)||a.score<0||a.score>100))||!Number.isFinite(Date.parse(a.at)))throw Error('Backup contains an invalid result.');if(p.lastActivity)p.lastActivity.href=safeActivityHref(p.lastActivity.href);for(const [id,s]of Object.entries(p.skills))if(!SKILLS[id]||!Number.isFinite(s.accuracy)||s.accuracy<0||s.accuracy>100)throw Error('Backup skill data is invalid.')}if(!Array.isArray(b.assignments)||!Array.isArray(b.classes))throw Error('Backup class data is invalid.');if(b.classes.length>100||b.assignments.length>2000)throw Error('Backup contains too many classroom records.');for(const c of b.classes){if(typeof c.id!=='string'||typeof c.name!=='string'||typeof c.code!=='string'||!Array.isArray(c.students)||!Array.isArray(c.tasks)||c.students.length>500||c.tasks.length>100)throw Error('Invalid classroom data.');for(const student of c.students)if(!validProfile(student)||(!student.local&&(!student.progress?.skills||!Array.isArray(student.progress?.activities))))throw Error('Invalid classroom learner.');for(const task of c.tasks)if(!SKILLS[task.skillId]||typeof task.id!=='string'||typeof task.title!=='string'||typeof task.dueDate!=='string')throw Error('Invalid classroom task.')}for(const a of b.assignments){if(typeof a.id!=='string'||typeof a.title!=='string'||!SKILLS[a.skillId]||typeof a.studentId!=='string')throw Error('Invalid assignment.');a.href=safeActivityHref(a.href)}return b}
export function importProgressBackup(raw){const b=validateBackup(raw);localStorage.setItem('atollingo_pre_import_backup',exportProgressBackup());saveFamily(b.family);writeLocal('atollingo_assignments',b.assignments);writeLocal('atollingo_classes',b.classes)}
export function downloadText(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
// Older app activities are completion evidence only: stars do not imply accuracy.
export function recordExternalCompletion(appName,activity,studentId){const f=getFamily();if(!f.profiles.some(p=>p.studentId===studentId))throw Error('Choose a learner first.');if(!['OceanLearn','OceanPlay','OceanArabic','Worksheets','MathLagoon'].includes(appName)||typeof activity.id!=='string'||activity.id.length>160||!Number.isInteger(activity.starsEarned)||activity.starsEarned<0||activity.starsEarned>3)throw Error('Invalid app completion.');const p=f.progress[studentId]||emptyProgress(),id=`external:${appName}:${activity.id}`;if(p.activities.some(a=>a.id===id))return;p.activities.push({id,skillId:'UNMAPPED',appName,score:null,starsEarned:activity.starsEarned,at:new Date().toISOString(),seconds:0});p.activities=p.activities.slice(-2000);p.stars+=activity.starsEarned;f.progress[studentId]=p;saveFamily(f)}
export function readActivityDraft(key,mode,total){const d=readLocal(key,null);return d&&Number.isInteger(d.step)&&d.step>=0&&d.step<=6&&Array.isArray(d.answers)&&d.answers.length<=total&&d.answers.every(a=>typeof a==='boolean')&&typeof d.id==='string'&&((d.step>=5&&d.answers.length===total)||(d.step<5&&d.answers.length<total))?d:{step:mode==='lesson'?0:4,answers:[],id:crypto.randomUUID(),saved:false}}

export function skillHref(id){return mathSkillResources[id]?.href||`/learn?skill=${encodeURIComponent(id)}`}
