'use client';
import {useEffect,useRef,useState} from 'react';
import {writeLocal} from '../utils/unifiedProgressTracker';
export const HUB_ORIGIN='https://atollingo.com';
let bridgeFrame=null,connectionWindow=null;
export function isConnectedApp(){return typeof window!=='undefined'&&['english.atollingo.com','play.atollingo.com','worksheets.atollingo.com','arabic.atollingo.com','lagoon.mathlagoon.com'].includes(location.hostname)}
export function request(action,activity){return new Promise((resolve,reject)=>{const target=connectionWindow&&!connectionWindow.closed?connectionWindow:bridgeFrame?.contentWindow;if(!target)return reject(Error('Connect to Atollingo before saving.'));const requestId=crypto.randomUUID();const timer=setTimeout(()=>{window.removeEventListener('message',receive);reject(Error('The hub could not be reached. Your result is kept here; reconnect to sync.'))},12000);function receive(e){if(e.origin!==HUB_ORIGIN||e.source!==target||e.data?.channel!=='atollingo-v1'||e.data.requestId!==requestId)return;clearTimeout(timer);window.removeEventListener('message',receive);if(e.data.error)reject(Error(e.data.error));else resolve(e.data)}window.addEventListener('message',receive);target.postMessage({channel:'atollingo-v1',requestId,action,activity},HUB_ORIGIN)})}
function cache(data){if(!data.profile)return;writeLocal('atollingo_family_v1',{version:1,familyId:data.profile.familyId,activeId:data.profile.studentId,profiles:[data.profile],progress:{[data.profile.studentId]:data.progress}})}
export async function completeConnected(activity){const key='atollingo_pending_result';writeLocal(key,activity);const data=await request('complete',activity);cache(data);localStorage.removeItem(key);return data}
export default function ConnectedBridge({children,onConnected}){const frame=useRef(null),[status,setStatus]=useState('Connecting your learning…'),[ready,setReady]=useState(false),[remote,setRemote]=useState(false);async function connect(){try{bridgeFrame=frame.current;const data=await request('read');if(!data.profile){setStatus('Choose your learner at Atollingo first, then reconnect.');return}cache(data);if(onConnected)onConnected(data.profile);const query=new URLSearchParams(location.search);if(location.pathname==='/connected'&&query.get('skill'))await request('begin',{skillId:query.get('skill'),mode:query.get('mode')||'lesson',title:query.get('skill')});const pending=JSON.parse(localStorage.getItem('atollingo_pending_result')||'null');if(pending&&pending.studentId===data.profile.studentId)await completeConnected(pending);setReady(true);setStatus(`Connected as ${data.profile.displayName}`)}catch(e){setStatus(e.message)}}useEffect(()=>{setRemote(isConnectedApp());if(!isConnectedApp()){setReady(true);setStatus('Learning on this device.');return}return()=>{bridgeFrame=null;connectionWindow=null}},[]);return <><div className="notice row"><span role="status">{status}</span><a href="https://atollingo.com/">Open learning hub</a>{remote&&<><button onClick={connect}>Reconnect</button><button onClick={()=>{connectionWindow=window.open(`${HUB_ORIGIN}/connect`,"atollingo-progress-connection","popup,width=560,height=640");if(connectionWindow)setStatus("In the connection window, wait for Ready, then choose Reconnect here. Keep that window open while learning.");else setStatus("Your browser blocked the connection window. Allow popups for this site, then try again.")}}>Open hub connection</button></>}</div>{remote&&<iframe title="Atollingo progress connection" src={`${HUB_ORIGIN}/bridge`} ref={frame} onLoad={connect} hidden/>}{ready?children:<p>Your activity will appear once your learner is connected.</p>}</>}
