'use client';
import {useEffect,useRef,useState} from 'react';
import {getProfile,recordActivityCompletion,setLastActivity,getConnectedNextStep,readActivityDraft,writeLocal} from '../utils/unifiedProgressTracker';
import {isConnectedApp,completeConnected} from './ConnectedBridge';
import AudioReadAloudButton from './AudioReadAloudButton';
import ReportProblemButton from './ReportProblemModal';
const steps=['Your goal','Learn','See an example','Try together','Try on your own','Your feedback','Next adventure'];
export default function LearningPathContainer({lesson,mode='lesson'}){
 const profile=getProfile(),key=`atollingo_draft_${profile.studentId}_${lesson.id}_${mode}`;
 const [draft,setDraft]=useState(()=>readActivityDraft(key,mode,mode==='lesson'?lesson.questions.length:lesson.game.length)),[choice,setChoice]=useState(null),[guided,setGuided]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);const start=useRef(0),locked=useRef(false);
 const questions=mode==='lesson'?lesson.questions:lesson.game,score=Math.round(draft.answers.filter(Boolean).length/questions.length*100),stars=score<60?1:score<=80?2:3;
 function change(next){try{writeLocal(key,next);setDraft(next);setError('')}catch{setError('This browser could not save your place. Please allow site storage.')}}
 useEffect(()=>{start.current=Date.now();try{setLastActivity({title:lesson.title,href:`/learn?skill=${lesson.id}&mode=${mode}`})}catch{setError('Your place could not be saved.')}},[lesson.id,lesson.title,mode]);
 function advance(){change({...draft,step:draft.step+1})}
 function answer(){if(choice===null||locked.current)return;locked.current=true;const answers=[...draft.answers,choice===questions[draft.answers.length].answer];change({...draft,answers,step:answers.length===questions.length?5:4});setChoice(null);queueMicrotask(()=>{locked.current=false})}
 async function save(){if(saving||draft.saved)return;setSaving(true);const activity={id:draft.id,studentId:profile.studentId,skillId:lesson.id,score,starsEarned:stars,seconds:Math.round((Date.now()-start.current)/1000)};try{if(isConnectedApp())await completeConnected(activity);else recordActivityCompletion(lesson.id,mode==='game'?'OceanPlay':mode==='worksheet'?'Worksheets':'OceanLearn',score,stars,activity);change({...draft,saved:true,step:6})}catch(e){setError(e.message)}finally{setSaving(false)}}
 const next=getConnectedNextStep(lesson.id);const q=questions[draft.answers.length];
 return <section className="learning-player panel"><div className="row"><a href={isConnectedApp()?"https://atollingo.com/learn":"/learn"}>← All skills</a><span>{mode==='lesson'?'Guided lesson':mode==='game'?'Word treasure game':'Digital worksheet'}</span></div><h1>{lesson.title}</h1><ol className="learning-steps" aria-label="Learning steps">{steps.map((s,i)=><li key={s} aria-current={i===draft.step?'step':undefined} className={i===draft.step?'current':''}>{i+1}. {s}</li>)}</ol><p className="muted">{lesson.outcome}</p><AudioReadAloudButton key={draft.step} text={draft.step===1?lesson.explanation.join(" "):draft.step===2?lesson.example.join(" "):draft.step===3?lesson.guided.prompt:draft.step===4?(q?.prompt||lesson.objective):lesson.objective}/>{error&&<p role="alert">{error}</p>}
 {draft.step===0&&<div className="lesson-content"><span className="large-symbol" aria-hidden="true">🐬</span><h2>{lesson.objective}</h2><p>Listen, try with Fizzy, then show what you know.</p><button className="primary" onClick={advance}>Let’s begin →</button></div>}
 {draft.step===1&&<div className="lesson-content"><h2>Discover the idea</h2>{lesson.explanation.map(t=><p key={t}>{t}</p>)}<button className="primary" onClick={advance}>See an example →</button></div>}
 {draft.step===2&&<div className="lesson-content"><h2>Watch how it works</h2><ol className="example-steps">{lesson.example.map(t=><li key={t}>{t}</li>)}</ol><button className="primary" onClick={advance}>Try with Fizzy →</button></div>}
 {draft.step===3&&<div className="lesson-content"><h2>⭐ Fizzy’s practice</h2><h3>{lesson.guided.prompt}</h3><div className="answer-options">{lesson.guided.options.map((o,i)=><button key={o} onClick={()=>setGuided(i)} aria-pressed={guided===i}>{o}</button>)}</div>{guided!==null&&<p role="status">{guided===lesson.guided.answer?'That’s right! You are ready to try on your own.':lesson.guided.hint}</p>}<button className="primary" disabled={guided!==lesson.guided.answer} onClick={advance}>Try on my own →</button></div>}
 {draft.step===4&&q&&<div className="lesson-content"><p>Question {draft.answers.length+1} of {questions.length}</p><progress value={draft.answers.length} max={questions.length} aria-label="Questions completed"/><h2>{q.prompt}</h2><fieldset className="answer-options"><legend className="sr-only">Choose one answer</legend>{q.options.map((o,i)=><label key={o} className={choice===i?'selected':''}><input type="radio" name={`answer-${draft.answers.length}`} checked={choice===i} onChange={()=>setChoice(i)}/>{o}</label>)}</fieldset><button className="primary" disabled={choice===null} onClick={answer}>{draft.answers.length===questions.length-1?'See my feedback':'Next question →'}</button></div>}
 {draft.step===5&&<div className="lesson-content"><p className="large-symbol" aria-label={`${stars} stars`}>{'⭐'.repeat(stars)}</p><h2>{score>=70?'You’re making waves!':'Every try helps you learn.'}</h2><p>You answered {draft.answers.filter(Boolean).length} of {questions.length} correctly.</p><ul>{questions.filter((_,i)=>!draft.answers[i]).slice(0,3).map(q=><li key={q.prompt}>{q.hint} The answer is “{q.options[q.answer]}”.</li>)}</ul><button className="primary" disabled={saving} onClick={save}>{saving?'Saving your progress…':'Save progress & continue →'}</button></div>}
 {draft.step===6&&<div className="lesson-content"><h2>Progress saved!</h2><p>{score<70?'Review the explanation, then have another go.':'Put your new skill to work in another activity.'}</p><div className="row">{next&&<a className="primary" href={next.href}>{next.title} →</a>}<button onClick={()=>{change({step:mode==='lesson'?0:4,answers:[],id:crypto.randomUUID(),saved:false});setGuided(null);start.current=Date.now()}}>Practise again</button><a href={isConnectedApp()?"https://atollingo.com/":"/"}>Return to my learning</a></div></div>}
 <ReportProblemButton resourceId={`${lesson.id}-${mode}`} title={lesson.title}/></section>
}
