import type {Challenge,Choice} from "./level1Games";
const meanings=[
 ['The lagoon was tranquil before the boats arrived. What does tranquil mean?','calm',['crowded','muddy'],'🌊','The water was quiet and still.'],['The fisher inspected the net before leaving. What does inspected mean?','checked carefully',['threw away','painted quickly'],'🎣','He looked closely for a problem.'],['The reef is fragile, so divers must be careful. What does fragile mean?','easily damaged',['very noisy','far away'],'🪸','It needs gentle care.'],['Aminath was eager to join the beach clean-up. What does eager mean?','excited and ready',['tired and sleepy','lost and confused'],'🏖️','She really wanted to begin.'],['The dhoni made a brief stop at the next island. What does brief mean?','short',['dangerous','late'],'⛵','The stop did not last long.'],['The turtle vanished beneath the blue water. What does vanished mean?','disappeared',['grew larger','made a sound'],'🐢','It could no longer be seen.'],['The class collected accurate information about rainfall. What does accurate mean?','correct',['funny','unfinished'],'📊','The information had no mistakes.'],['The palm provided shelter from the hot sun. What does shelter mean?','protection',['decoration','direction'],'🌴','The shade kept them safe from heat.']
];
const sentences=[
 ['Improve: The heron walked.','The tall heron stepped quietly across the wet sand.',['The heron thing did stuff.','Heron walked sand.'],'🐦','Add precise details about how and where.'],['Improve: We saw fish.','We spotted five silver fish beside the coral reef.',['Fish were there maybe.','We saw stuff in water.'],'🐠','Add number, colour, and place.'],['Improve: The rain came.','Heavy rain drummed loudly on the classroom roof.',['Rain rain rain.','The came rain.'],'🌧️','Use an adjective and a strong verb.'],['Improve: Hassan spoke.','Hassan clearly explained his clean-beach plan to the class.',['Hassan said a thing.','Spoke Hassan plan.'],'🗣️','Explain how, what, and to whom.'],['Improve: The boat moved.','The wooden dhoni glided smoothly across the calm lagoon.',['Boat went over there.','The moving boat moved.'],'⛵','Replace moved with a vivid verb.'],['Improve: Mariyam found a shell.','At low tide, Mariyam discovered a tiny striped shell.',['Mariyam got it.','Shell found Mariyam.'],'🐚','Add when and a visual detail.'],['Improve: Children cleaned.','After lunch, the children carefully sorted plastic from leaves.',['Children did cleaning.','Cleaned they things.'],'🧹','Say when, how, and what.'],['Improve: A crab ran.','A bright red crab scuttled sideways into a sandy hole.',['The crab runned fast.','Crab did run.'],'🦀','Use an exact movement verb.']
];
const reading=[
 ['Nisha carried a basket of mangoes to her grandmother. A cheeky crow landed beside it. Nisha covered the basket and offered the crow one small piece.','Why did Nisha cover the basket?','to protect the mangoes',['to make it heavier','to hide from her grandmother'],'🥭'],['During a reef visit, Ali noticed a plastic bag near a turtle. He told the guide, who safely removed it with a tool.','What responsible action did Ali take?','he alerted the guide',['he touched the turtle','he left the bag there'],'🐢'],['A sudden shower began during football practice. The team moved their bags under the pavilion, then laughed as the ball splashed through puddles.','Where did the team put its bags?','under the pavilion',['inside a dhoni','beside the goal'],'⚽'],['Mariyam planted two chilli seeds. She watered both, but placed only one pot near sunlight. The sunny pot sprouted first.','Why did one pot sprout first?','it received sunlight',['it had no soil','it was never watered'],'🌱'],['Hassan borrowed a library book about whales. He wrote the return date on his calendar and returned it before the date.','What helped Hassan return the book on time?','his calendar note',['a whale poster','the beach bell'],'📚'],['The island shop ran out of paper bags. The owner asked customers to bring baskets until new bags arrived.','Why did customers bring baskets?','the shop had no paper bags',['the baskets were free','the shop sold fish'],'🧺']
];
const speaking=[
 ['Your group must choose a beach-cleaning time. What is the clearest suggestion?','Let’s meet at 4 p.m. when the sand is cooler.',['Do something later.','Maybe a time somewhere.'],'🕓','Give an exact time and a reason.'],['A visitor asks where the jetty is. What is the clearest reply?','Walk straight, then turn left beside the mosque.',['It is over there.','Go somewhere near water.'],'⚓','Use ordered directions and a landmark.'],['You disagree with a friend about feeding reef fish. What is respectful?','I understand your idea, but feeding can harm the reef.',['That is silly.','You are completely wrong.'],'🐠','Acknowledge the friend before explaining.'],['Your team finished a poster. How should you present it?','Our poster shows three ways to save water.',['This is some stuff.','Look at it yourself.'],'🎤','State the topic and number of ideas.'],['You need help carrying books. What should you say?','Could you please help me carry these books?',['Carry these now.','Books are heavy.'],'📚','Make a polite, complete request.'],['A classmate gives a good idea. What is a useful response?','I like that idea because it keeps the beach clean.',['Okay.','Whatever you say.'],'💬','Say what you value and why.']
];
const rotate=<T,>(a:T[],n:number)=>a.map((_,i)=>a[(i+n)%a.length]);
const options=(answer:string,wrong:string[],icon:string,seed:number):Choice[]=>rotate([{id:answer,label:answer,icon},...wrong.slice(0,2).map((x,i)=>({id:`wrong-${i}`,label:x,icon:i?'🫧':'⭐'}))],seed%3);
export function level5Challenge(game:number,stage:number,index:number):Challenge{const seed=(stage-1)*5+index;if(game===0){const x=meanings[seed%meanings.length];return{id:`l5-meaning-${stage}-${index}`,prompt:x[0] as string,instruction:'Use the sentence clue to match the meaning.',hint:x[4] as string,audio:x[0] as string,answer:x[1] as string,choices:options(x[1] as string,x[2] as string[],x[3] as string,seed)}}if(game===1){const x=sentences[seed%sentences.length];return{id:`l5-sentence-${stage}-${index}`,prompt:x[0] as string,instruction:'Choose the strongest revised sentence.',hint:x[4] as string,audio:x[0] as string,answer:x[1] as string,choices:options(x[1] as string,x[2] as string[],x[3] as string,seed)}}if(game===2){const x=reading[seed%reading.length];return{id:`l5-reading-${stage}-${index}`,prompt:`${x[0]} ${x[1]}`,instruction:'Read the short island story and choose the evidence-based answer.',hint:'Look back for the action or reason stated in the story.',audio:`${x[0]} ${x[1]}`,answer:x[2] as string,choices:options(x[2] as string,x[3] as string[],x[4] as string,seed)}}const x=speaking[seed%speaking.length];return{id:`l5-speaking-${stage}-${index}`,prompt:x[0] as string,instruction:'Choose what you would say aloud.',hint:x[4] as string,audio:x[0] as string,answer:x[1] as string,choices:options(x[1] as string,x[2] as string[],x[3] as string,seed)}}
