import type {Challenge,Choice} from "./level1Games";
const evidence=[
 ['Claim: The island library is popular. Which detail is strongest evidence?','It recorded 240 visits in June.',['The walls are blue.','It stands near a palm.'],'📚','Choose a measurable fact that directly supports popular.'],
 ['Claim: The reef clean-up was effective. Which evidence is strongest?','Volunteers removed 36 bags of rubbish.',['The boat was yellow.','Lunch began at noon.'],'🪸','Look for a result of the clean-up.'],
 ['Claim: The new rain tank saves water. Which detail proves it?','The school used 400 fewer litres from the mains.',['The tank is round.','Rain fell on Tuesday.'],'🌧️','A comparison in water use is useful evidence.'],
 ['Claim: Turtle nests need protection. Which evidence best supports it?','Fewer hatchlings reached the sea on brightly lit beaches.',['Turtles have four flippers.','Beach sand is warm.'],'🐢','Choose evidence showing harm or benefit.'],
 ['Claim: Walking to school improved attendance. Which fact supports it?','Late arrivals fell from 18 to 5 each week.',['Students wore shoes.','The gate opens east.'],'🚶','Compare attendance before and after.'],
 ['Claim: Mangroves protect island shores. Which evidence is strongest?','Shorelines with mangroves lost less sand during storms.',['Mangrove leaves are green.','Crabs live near roots.'],'🌿','Find the fact about shore protection.'],
 ['Claim: Reading daily improved fluency. Which evidence proves it?','The class read 22 more words per minute after six weeks.',['The books had pictures.','Reading happened indoors.'],'📖','Choose the measured improvement.'],
 ['Claim: Reusable bags reduced waste. Which evidence supports it?','Plastic bag waste dropped by half in one month.',['Baskets have handles.','The shop sells mangoes.'],'🧺','Look for a change in waste.']
];
const edits=[
 ['Fix the sentence: yesterday aminath visited malé.','Yesterday, Aminath visited Malé.',['Yesterday Aminath, visited malé.','yesterday, aminath visited Malé'],'✏️','Capitalise the first word, names and place; add punctuation.'],
 ['Choose the clearest sentence.','The guide showed us where the turtles nested.',['The guide showed us where they nested them.','Where turtles the guide showed nested.'],'🐢','Check word order and avoid an unclear pronoun.'],
 ['Fix subject–verb agreement.','The group of students is cleaning the beach.',['The group of students are cleaning the beach.','The group of students be cleaning the beach.'],'🧹','The subject is the singular word group.'],
 ['Join the ideas correctly: It rained. We continued playing.','Although it rained, we continued playing.',['Although it rained, but we continued playing.','It rained although and we continued.'],'🌧️','Although already shows contrast.'],
 ['Remove the unnecessary repetition.','The dhoni crossed the lagoon quickly.',['The dhoni quickly crossed across the lagoon quickly.','The dhoni crossed the lagoon across.'],'⛵','Keep each idea only once.'],
 ['Choose the correctly punctuated dialogue.','“Please close the gate,” said Hassan.',['“Please close the gate” said Hassan.','Please close, “the gate,” said Hassan.'],'💬','Speech marks contain the spoken words.'],
 ['Choose the precise pronoun.','Mariyam gave the map to Hassan and me.',['Mariyam gave the map to Hassan and I.','Mariyam gave the map to he and me.'],'🗺️','After to, use the object pronoun me.'],
 ['Fix the misplaced modifier.','Wearing a blue cap, Ali watched the dolphin.',['Ali watched the dolphin wearing a blue cap.','The dolphin watched Ali wearing blue.'],'🐬','Place the description beside the person it describes.']
];
const summaries=[
 ['A class surveyed litter for three days. Plastic wrappers were most common, so students placed labelled bins near the shop and school. A week later, wrapper litter had decreased.','Students used survey results to place bins and reduce wrapper litter.',['Students visited the shop for three days.','The school has labels and wrappers.'],'🗑️'],
 ['Strong wind delayed the morning ferry. The captain waited until conditions improved, checked the safety equipment, and then crossed the channel safely.','The captain delayed the ferry and travelled after conditions became safer.',['The ferry always travels in strong wind.','The captain bought new equipment.'],'⛴️'],
 ['A reef club photographed coral each month. After noticing damage near an anchor point, members asked boats to use a safer mooring area.','Reef observations led the club to recommend safer boat mooring.',['The club bought a camera every month.','All coral damage is caused by photos.'],'📷'],
 ['The school garden wilted during a dry week. Students covered the soil with coconut husk and watered early in the morning, helping it retain moisture.','Students conserved moisture with coconut husk and early watering.',['The garden grew only coconuts.','Students stopped watering the plants.'],'🌱'],
 ['Aminath compared two reports about turtles. One cited a wildlife survey; the other made claims without sources. She used the surveyed report.','Aminath selected the report supported by a reliable survey.',['Aminath wrote two turtle surveys.','Both reports contained the same evidence.'],'📑'],
 ['Residents noticed fewer fish near a seagrass bed after boats began crossing it. They marked a route around the habitat and fish numbers later increased.','A new boat route protected seagrass habitat and fish numbers recovered.',['Residents stopped using all boats.','Fish prefer routes painted on water.'],'🐟']
];
const discussions=[
 ['A teammate says school should ban all plastic immediately. Which response advances the discussion?','Could we begin with single-use bags and measure the change?',['That idea will never work.','Plastic is bad, so yes.'],'🗣️','Build on the idea with a practical, measurable step.'],
 ['Someone claims every reef visit causes damage. What is the best response?','What evidence distinguishes careful guided visits from harmful ones?',['You are wrong about everything.','Reefs are pretty.'],'🤿','Ask for evidence and clarify the broad claim.'],
 ['Your group has two different poster designs. What should the captain say?','Let’s compare which design makes our key message easiest to understand.',['Mine is obviously better.','Choose one quickly.'],'🎨','Set a fair criterion for the decision.'],
 ['A quiet classmate has not spoken. What supports participation?','Mariyam, would you like to share your idea or pass for now?',['Mariyam must answer now.','We do not need her idea.'],'🤝','Invite respectfully and allow choice.'],
 ['The group drifts away from the topic. What should the captain say?','Let’s return to our question about saving water at school.',['Stop talking.','Water is blue.'],'💧','Name the shared question and redirect calmly.'],
 ['Two sources give different rainfall totals. What is the best next step?','Check each source’s date and measurement method.',['Choose the larger number.','Average them without checking.'],'📊','Investigate why the evidence differs.'],
 ['A teammate changes their opinion after hearing evidence. How should you respond?','Thank you for reconsidering the evidence with us.',['You should have agreed earlier.','That means you lost.'],'💬','Changing a view after evidence is responsible.'],
 ['The group must finish with a shared decision. What should happen?','Summarise agreements, remaining concerns and the final action.',['Repeat every sentence said.','Let one person decide silently.'],'✅','A conclusion should capture consensus and next steps.']
];
const rotate=<T,>(a:T[],n:number)=>a.map((_,i)=>a[(i+n)%a.length]);
const options=(answer:string,wrong:string[],icon:string,seed:number):Choice[]=>rotate([{id:answer,label:answer,icon},...wrong.slice(0,2).map((x,i)=>({id:`wrong-${i}`,label:x,icon:i?'🫧':'⭐'}))],seed%3);
export function level6Challenge(game:number,stage:number,index:number):Challenge{const seed=(stage-1)*5+index;if(game===0){const x=evidence[seed%evidence.length];return{id:`l6-evidence-${stage}-${index}`,prompt:x[0] as string,instruction:'Inspect the evidence and select the strongest support.',hint:x[4] as string,audio:x[0] as string,answer:x[1] as string,choices:options(x[1] as string,x[2] as string[],x[3] as string,seed)}}if(game===1){const x=edits[seed%edits.length];return{id:`l6-editor-${stage}-${index}`,prompt:x[0] as string,instruction:'Tap the correctly edited sentence.',hint:x[4] as string,audio:x[0] as string,answer:x[1] as string,choices:options(x[1] as string,x[2] as string[],x[3] as string,seed)}}if(game===2){const x=summaries[seed%summaries.length];return{id:`l6-summary-${stage}-${index}`,prompt:x[0] as string,instruction:'Choose the summary containing the main idea and essential result.',hint:'Remove small details; keep the problem, action and outcome.',audio:x[0] as string,answer:x[1] as string,choices:options(x[1] as string,x[2] as string[],x[3] as string,seed)}}const x=discussions[seed%discussions.length];return{id:`l6-discussion-${stage}-${index}`,prompt:x[0] as string,instruction:'Choose the response that moves the discussion forward.',hint:x[4] as string,audio:x[0] as string,answer:x[1] as string,choices:options(x[1] as string,x[2] as string[],x[3] as string,seed)}}
