import type {Challenge,Choice} from "./level1Games";
const literary=[
 ['“The lagoon held the moon like a silver coin.” Which technique is used?','simile',['fact','command'],'🌙','Like makes a comparison.'],['A storm arrives whenever the main character ignores advice. What role does the storm play?','it develops the story’s conflict',['it lists instructions','it gives a definition'],'⛈️','Consider how the event creates a problem.'],['In the beginning Ali fears deep water; later he calmly helps a younger swimmer. What changed?','Ali became more confident',['Ali forgot how to swim','the water disappeared'],'🏊','Compare his behaviour at the beginning and end.'],['“The palms whispered warnings in the wind.” Which technique is used?','personification',['a statistic','a heading'],'🌴','The trees are given a human action.'],['A story repeatedly shows a cracked compass before the boat gets lost. Why?','it foreshadows the later problem',['it proves the compass is new','it changes the setting to school'],'🧭','An early clue hints at what will happen.'],['Two characters clean the same beach: one seeks praise, the other wants to protect turtles. What differs?','their motivation',['the setting','the weather'],'🐢','Ask why each character acts.'],['The narrator says the crab is “the island’s bravest guard,” but it hides from a leaf. What creates humour?','the contrast between the claim and action',['a scientific explanation','alphabetical order'],'🦀','The action is opposite to the description.'],['A poem returns to the line “The sea remembers.” What does repetition emphasise?','the central idea',['the page number','the author’s address'],'🌊','Repeated words draw attention to a theme.']
];
const precision=[
 ['Replace “went”: The dhoni went across the rough channel.','surged',['existed','was'],'⛵','Choose a verb showing strong movement through water.'],['Choose the most precise description.','Three juvenile turtles crawled toward the moonlit tide.',['Some turtles went there.','Animals moved near water.'],'🐢','Prefer exact number, age, movement and setting.'],['Which transition shows contrast?','however',['therefore','for example'],'🔀','The writer is about to present a different idea.'],['Replace the vague word “nice.”','welcoming',['thing','okay'],'🏡','Choose a word describing the feeling precisely.'],['Which sentence has the most suitable formal tone?','The survey indicates a decline in plastic waste.',['Our survey says rubbish went way down!','Stuff got better, you know.'],'📊','A report uses objective, specific language.'],['Choose the clearest cause-and-effect link.','Because the channel was shallow, the captain reduced speed.',['The channel was shallow, meanwhile speed.','The captain reduced because channel.'],'⚓','Connect the reason and result grammatically.'],['Which word best shows uncertainty?','possibly',['definitely','always'],'🤔','The evidence does not allow complete certainty.'],['Choose the strongest concluding phrase.','Taken together, the evidence supports reef protection.',['And that is all.','Reefs, reefs, reefs.'],'🪸','Synthesize the evidence and return to the claim.']
];
const critical=[
 ['A poster funded by a bottled-water company says disposable bottles create no waste problem. What should you check first?','the sponsor’s possible bias',['the poster colour','the size of the logo'],'🧴','Ask who benefits from the claim.'],['Two websites disagree about turtle numbers. Which source is more reliable?','a recent wildlife survey explaining its method',['an undated anonymous post','a shop advertisement'],'🐢','Prefer current evidence with a transparent method.'],['After bins were installed, beach litter fell. Can we prove the bins caused all of the change?','no; other changes should also be checked',['yes; events after one another always have one cause','no; measurements are never useful'],'🗑️','Sequence alone does not prove a single cause.'],['A class surveys only its ten best swimmers about swimming confidence. What is the problem?','the sample is biased',['the question uses English','ten is an even number'],'🏊','The group surveyed does not represent all students.'],['“Everyone prefers online books,” says one student. What evidence is needed?','responses from a representative group',['one more personal opinion','a picture of a tablet'],'💻','A broad claim needs broad evidence.'],['A graph begins its vertical axis at 95 instead of 0, making a small change look huge. What should readers notice?','the scale may exaggerate the difference',['the bars use blue','the title is centred'],'📈','Check how the axis affects visual comparison.'],['A report uses a 2010 rainfall record to describe this year. What is its main weakness?','the evidence may be outdated',['rainfall uses numbers','the record has a date'],'🌧️','Evidence should fit the time of the claim.'],['Which question best tests a reef-restoration claim?','Did coral cover increase compared with a similar untreated area?',['Was the project logo attractive?','Did volunteers enjoy lunch?'],'🪸','Compare a relevant outcome with a suitable control.']
];
const author=[
 ['You want readers to feel tension before a storm. Which opening works best?','The wind stopped. Even the reef birds fell silent.',['It was a stormy day.','Storms have wind and rain.'],'⛈️','Withhold the event and build an uneasy mood.'],['Which detail best reveals character without directly naming a trait?','Hassan returned the lost wallet without opening it.',['Hassan was honest.','Honesty is good.'],'👛','Show the trait through an action.'],['Which ending best echoes an opening about a broken compass?','At home, Mariyam hung the repaired compass beside her map.',['Then everything ended.','Compasses point north.'],'🧭','Return to the opening image with a meaningful change.'],['Which dialogue sounds natural and advances the plot?','“The tide is rising,” Ali warned. “We need the higher path.”',['“Hello,” Ali said. “Hello,” Nisha replied.','“I am explaining the plot now,” Ali said.'],'🌊','Dialogue should reveal useful information or choice.'],['Choose the best sensory detail for a fish market.','Salt air mixed with the sharp scent of limes and grilled tuna.',['The market was sensory.','There were things to smell.'],'🐟','Use specific smells and tastes.'],['Which sentence varies pace for an exciting moment?','The rope snapped. The sail dropped. Everyone ducked.',['The rope snapped and then the sail dropped and everyone ducked eventually.','An event occurred on the boat.'],'⛵','Short sentences accelerate action.'],['Which revision creates a stronger viewpoint?','From beneath the jetty, the kitten saw only boots and splashing water.',['There was a jetty and a kitten.','People walked above an animal.'],'🐈','Filter details through what the character can perceive.'],['Which title creates curiosity without revealing everything?','The Bell Beneath the Lagoon',['A Story About Finding a Bell Underwater','Things That Happened Tuesday'],'🔔','Hint at the central mystery.']
];
const rotate=<T,>(a:T[],n:number)=>a.map((_,i)=>a[(i+n)%a.length]);
const options=(answer:string,wrong:string[],icon:string,seed:number):Choice[]=>rotate([{id:answer,label:answer,icon},...wrong.slice(0,2).map((x,i)=>({id:`wrong-${i}`,label:x,icon:i?'🫧':'⭐'}))],seed%3);
export function level7Challenge(game:number,stage:number,index:number):Challenge{const seed=(stage-1)*5+index,x=(game===0?literary:game===1?precision:game===2?critical:author)[seed%8];return{id:`l7-${game}-${stage}-${index}`,prompt:x[0] as string,instruction:game===0?'Interpret the literary clue.':game===1?'Choose the most precise language.':game===2?'Evaluate the claim and evidence.':'Choose the strongest author craft.',hint:x[4] as string,audio:x[0] as string,answer:x[1] as string,choices:options(x[1] as string,x[2] as string[],x[3] as string,seed)}}
