"use client";
import {useEffect,useMemo,useState} from "react";

type Profile={name:string;grade:number;difficulty:"Easy"|"Medium"|"Hard";avatar:string};
const AVATARS=["🧕","👧","👦","🧒","👩🏽‍🦱","👦🏾"];
const LEVELS=[
 ["Color Splash","Island Animal Match","Rhyme Time Reef","Follow the Island Guide"],
 ["Word Builder Bay","Sentence Scrambler","Preposition Playground","Picture Story Path"],
 ["Word Detective Reef","Time-Order Twister","Island Community Tree","Text Feature Treasure Hunt"],
 ["Grammar Lightning","Opinion Island","Atoll Explorer","Poster & Diagram Studio"],
 ["Meaning Match Lagoon","Super Sentences","Island Book Club","Speak Up Studio"],
 ["Evidence Explorer","Editor’s Desk","Summary Current","Discussion Captain"],
 ["Literary Explorer","Precision Language Lab","Critical Thinker","Author’s Workshop"],
];
const ICONS=[["🎨","🐢","🎵","🐬"],["🔤","🧩","🎯","🖼️"],["🔎","⏳","🏝️","📖"],["⚡","💬","🧭","🎬"],["🧠","✍️","📚","🎤"],["🔍","📝","🌊","🗣️"],["📘","🎯","🧩","🏛️"]];
function mapLevel(g:number,d:string){return Math.max(0,Math.min(6,g+(d==="Easy"?-1:d==="Hard"?1:0)-1))}
export default function OceanPlayApp(){
 const[profile,setProfile]=useState<Profile|null>(null),[draft,setDraft]=useState<Profile>({name:"",grade:1,difficulty:"Medium",avatar:AVATARS[0]}),[game,setGame]=useState<number|null>(null);
 const[progress,setProgress]=useState<Record<string,number>>({});
 useEffect(()=>{const p=localStorage.getItem("oceanplay-profile"),s=localStorage.getItem("oceanplay-progress");if(p)setProfile(JSON.parse(p));if(s)setProgress(JSON.parse(s))},[]);
 const level=profile?mapLevel(profile.grade,profile.difficulty):0,total=Object.values(progress).reduce((a,b)=>a+b,0);
 const save=()=>{if(!draft.name.trim())return;localStorage.setItem("oceanplay-profile",JSON.stringify(draft));setProfile(draft)};
 if(!profile)return <main className="login-shell"><section className="login-card"><div className="logo-orbit">🐬<span>🎮</span></div><p className="eyebrow">WELCOME TO</p><h1>OceanPlay</h1><p className="lead">Play, laugh and grow your English around the islands.</p><label>Your name<input value={draft.name} placeholder="Type your name" onChange={e=>setDraft({...draft,name:e.target.value})}/></label><fieldset><legend>Choose your grade</legend><div className="grade-row">{[1,2,3,4,5].map(n=><button key={n} className={draft.grade===n?"selected":""} onClick={()=>setDraft({...draft,grade:n})}>G{n}</button>)}</div></fieldset><fieldset><legend>Choose difficulty</legend><div className="choice-row">{(["Easy","Medium","Hard"] as const).map(d=><button key={d} className={draft.difficulty===d?"selected":""} onClick={()=>setDraft({...draft,difficulty:d})}>{d}</button>)}</div></fieldset><fieldset><legend>Choose your player</legend><div className="avatar-row">{AVATARS.map(a=><button key={a} className={draft.avatar===a?"selected":""} onClick={()=>setDraft({...draft,avatar:a})}>{a}</button>)}</div></fieldset><button className="primary" onClick={save}>Start island games →</button></section></main>;
 const games=LEVELS[level];
 return <main className="app-shell"><header><button className="icon-btn" onClick={()=>setGame(null)}>🏠<small>Home</small></button><div className="score">⭐ {total} <span>🏅 {Math.floor(total/12)}</span></div><div className="student"><b>{profile.avatar}</b><div><strong>Hi, {profile.name}</strong><small>G{profile.grade} · {profile.difficulty[0]} · L{level+1}</small></div></div><button className="icon-btn" onClick={()=>{if(confirm("Reset OceanPlay stars?")){setProgress({});localStorage.removeItem("oceanplay-progress")}}}>🫧<small>Reset</small></button><button className="icon-btn" onClick={()=>{localStorage.removeItem("oceanplay-profile");setProfile(null)}}>🚪<small>Logout</small></button></header>{game===null?<IslandMap level={level} games={games} progress={progress} onGame={setGame}/>:<StageMap game={game} title={games[game]} icon={ICONS[level][game]} level={level} progress={progress} setProgress={p=>{setProgress(p);localStorage.setItem("oceanplay-progress",JSON.stringify(p))}} onBack={()=>setGame(null)}/>}<nav><button onClick={()=>setGame(null)}>🎮<span>Games</span></button><button onClick={()=>setGame(null)}>🏝️<span>Map</span></button><button>🏆<span>Rewards</span></button><button>📈<span>Progress</span></button></nav></main>
}
function IslandMap({level,games,progress,onGame}:{level:number;games:string[];progress:Record<string,number>;onGame:(n:number)=>void}){return <section className="map"><div className="map-title"><p className="eyebrow">CURRICULUM LEVEL {level+1}</p><h1>Choose a game island</h1><p>Four playful ways to practise this level’s English skills.</p></div><div className="islands">{games.map((g,i)=><button key={g} className={`island i${i}`} onClick={()=>onGame(i)}><span>{ICONS[level][i]}</span><strong>{g}</strong><small>{progress[`${level}-${i}`]||0}/20 stages</small><i>{i===0?"Play now →":"Explore →"}</i></button>)}</div></section>}
function StageMap({game,title,icon,level,progress,setProgress,onBack}:{game:number;title:string;icon:string;level:number;progress:Record<string,number>;setProgress:(p:Record<string,number>)=>void;onBack:()=>void}){const key=`${level}-${game}`,done=progress[key]||0;return <section className="stages"><button className="back" onClick={onBack}>← Game islands</button><div className="stage-head"><span>{icon}</span><div><p className="eyebrow">LEVEL {level+1} GAME</p><h1>{title}</h1><p>20 stages · 5 challenges each · unlock with 3/5</p></div></div><div className="phase"><b>🐚 Phase 1</b><span>Stages 1–7 · Foundations</span></div><StageButtons from={1} to={7} done={done} onPlay={n=>setProgress({...progress,[key]:Math.max(done,n)})}/><div className="phase coral"><b>🪸 Phase 2</b><span>Stages 8–14 · Core skills</span></div><StageButtons from={8} to={14} done={done} onPlay={n=>setProgress({...progress,[key]:Math.max(done,n)})}/><div className="phase pearl"><b>🦪 Phase 3</b><span>Stages 15–20 · Full mastery</span></div><StageButtons from={15} to={20} done={done} onPlay={n=>setProgress({...progress,[key]:Math.max(done,n)})}/></section>}
function StageButtons({from,to,done,onPlay}:{from:number;to:number;done:number;onPlay:(n:number)=>void}){return <div className="stage-grid">{Array.from({length:to-from+1},(_,i)=>from+i).map(n=>{const locked=n>done+1;return <button key={n} disabled={locked} className={n<=done?"complete":n===done+1?"next":""} onClick={()=>onPlay(n)}><span>{n<=done?"⭐":locked?"🔒":n}</span><small>Stage {n}</small></button>})}</div>}
